{"title": "A Dance with Dragons", "chapter": "ADWD 1: Prologue", "score": "Score: 8.09"}
{"title": "A Dance with Dragons", "chapter": "ADWD 2: Tyrion I", "score": "Score: 8.01"}
{"title": "A Dance with Dragons", "chapter": "ADWD 3: Daenerys I", "score": "Score: 7.25"}
{"title": "A Dance with Dragons", "chapter": "ADWD 4: Jon I", "score": "Score: 8.12"}
{"title": "A Dance with Dragons", "chapter": "ADWD 5: Bran I", "score": "Score: 8.14"}
{"title": "A Dance with Dragons", "chapter": "ADWD 6: Tyrion II", "score": "Score: 7.51"}
{"title": "A Dance with Dragons", "chapter": "ADWD 7: The Merchant's Man", "score": "Score: 7.02"}
{"title": "A Dance with Dragons", "chapter": "ADWD 8: Jon II", "score": "Score: 9.13"}
{"title": "A Dance with Dragons", "chapter": "ADWD 9: Tyrion III", "score": "Score: 7.62"}
{"title": "A Dance with Dragons", "chapter": "ADWD 10: Davos I", "score": "Score: 8.21"}
{"title": "A Dance with Dragons", "chapter": "ADWD 11: Jon III", "score": "Score: 7.95"}
{"title": "A Dance with Dragons", "chapter": "ADWD 12: Daenerys II", "score": "Score: 7.50"}
{"title": "A Dance with Dragons", "chapter": "ADWD 13: Reek I", "score": "Score: 8.30"}
{"title": "A Dance with Dragons", "chapter": "ADWD 14: Bran II", "score": "Score: 8.89"}
{"title": "A Dance with Dragons", "chapter": "ADWD 15: Tyrion IV", "score": "Score: 7.59"}
{"title": "A Dance with Dragons", "chapter": "ADWD 16: Davos II", "score": "Score: 7.71"}
{"title": "A Dance with Dragons", "chapter": "ADWD 17: Daenerys III", "score": "Score: 7.46"}
{"title": "A Dance with Dragons", "chapter": "ADWD 18: Jon IV", "score": "Score: 8.01"}
{"title": "A Dance with Dragons", "chapter": "ADWD 19: Tyrion V", "score": "Score: 7.92"}
{"title": "A Dance with Dragons", "chapter": "ADWD 20: Davos III", "score": "Score: 8.61"}
{"title": "A Dance with Dragons", "chapter": "ADWD 21: Reek II", "score": "Score: 8.39"}
{"title": "A Dance with Dragons", "chapter": "ADWD 22: Jon V", "score": "Score: 7.53"}
{"title": "A Dance with Dragons", "chapter": "ADWD 23: Tyrion VI", "score": "Score: 7.77"}
{"title": "A Dance with Dragons", "chapter": "ADWD 24: Daenerys IV", "score": "Score: 6.44"}
{"title": "A Dance with Dragons", "chapter": "ADWD 25: The Lost Lord", "score": "Score: 8.38"}
{"title": "A Dance with Dragons", "chapter": "ADWD 26: The Windblown", "score": "Score: 7.32"}
{"title": "A Dance with Dragons", "chapter": "ADWD 27: The Wayward Bride", "score": "Score: 8.62"}
{"title": "A Dance with Dragons", "chapter": "ADWD 28: Tyrion VII", "score": "Score: 8.27"}
{"title": "A Dance with Dragons", "chapter": "ADWD 29: Jon VI", "score": "Score: 8.36"}
{"title": "A Dance with Dragons", "chapter": "ADWD 30: Davos IV", "score": "Score: 9.33"}
{"title": "A Dance with Dragons", "chapter": "ADWD 31: Daenerys V", "score": "Score: 6.65"}
{"title": "A Dance with Dragons", "chapter": "ADWD 32: Melisandre I", "score": "Score: 8.85"}
{"title": "A Dance with Dragons", "chapter": "ADWD 33: Reek III", "score": "Score: 8.35"}
{"title": "A Dance with Dragons", "chapter": "ADWD 34: Tyrion VIII", "score": "Score: 7.58"}
{"title": "A Dance with Dragons", "chapter": "ADWD 35: Bran III", "score": "Score: 9.08"}
{"title": "A Dance with Dragons", "chapter": "ADWD 36: Jon VII", "score": "Score: 7.44"}
{"title": "A Dance with Dragons", "chapter": "ADWD 37: Daenerys VI", "score": "Score: 6.01"}
{"title": "A Dance with Dragons", "chapter": "ADWD 38: The Prince of Winterfell", "score": "Score: 8.46"}
{"title": "A Dance with Dragons", "chapter": "ADWD 39: The Watcher", "score": "Score: 8.36"}
{"title": "A Dance with Dragons", "chapter": "ADWD 40: Jon VIII", "score": "Score: 7.92"}
{"title": "A Dance with Dragons", "chapter": "ADWD 41: Tyrion IX", "score": "Score: 7.03"}
{"title": "A Dance with Dragons", "chapter": "ADWD 42: The Turncloak", "score": "Score: 8.42"}
{"title": "A Dance with Dragons", "chapter": "ADWD 43: The King's Prize", "score": "Score: 7.52"}
{"title": "A Dance with Dragons", "chapter": "ADWD 44: Daenerys VII", "score": "Score: 6.58"}
{"title": "A Dance with Dragons", "chapter": "ADWD 45: Jon IX", "score": "Score: 8.08"}
{"title": "A Dance with Dragons", "chapter": "ADWD 46: The Blind Girl", "score": "Score: 8.67"}
{"title": "A Dance with Dragons", "chapter": "ADWD 47: A Ghost in Winterfell", "score": "Score: 8.90"}
{"title": "A Dance with Dragons", "chapter": "ADWD 48: Tyrion X", "score": "Score: 7.98"}
{"title": "A Dance with Dragons", "chapter": "ADWD 49: Jaime I", "score": "Score: 8.63"}
{"title": "A Dance with Dragons", "chapter": "ADWD 50: Jon X", "score": "Score: 7.94"}
{"title": "A Dance with Dragons", "chapter": "ADWD 51: Daenerys VIII", "score": "Score: 6.82"}
{"title": "A Dance with Dragons", "chapter": "ADWD 52: Theon I", "score": "Score: 9.26"}
{"title": "A Dance with Dragons", "chapter": "ADWD 53: Daenerys IX", "score": "Score: 9.21"}
{"title": "A Dance with Dragons", "chapter": "ADWD 54: Jon XI", "score": "Score: 8.23"}
{"title": "A Dance with Dragons", "chapter": "ADWD 55: Cersei I", "score": "Score: 7.86"}
{"title": "A Dance with Dragons", "chapter": "ADWD 56: The Queensguard", "score": "Score: 7.93"}
{"title": "A Dance with Dragons", "chapter": "ADWD 57: The Iron Suitor", "score": "Score: 7.71"}
{"title": "A Dance with Dragons", "chapter": "ADWD 58: Tyrion XI", "score": "Score: 8.03"}
{"title": "A Dance with Dragons", "chapter": "ADWD 59: Jon XII", "score": "Score: 8.24"}
{"title": "A Dance with Dragons", "chapter": "ADWD 60: The Discarded Knight", "score": "Score: 7.85"}
{"title": "A Dance with Dragons", "chapter": "ADWD 61: The Spurned Suitor", "score": "Score: 7.11"}
{"title": "A Dance with Dragons", "chapter": "ADWD 62: The Griffin Reborn", "score": "Score: 8.38"}
{"title": "A Dance with Dragons", "chapter": "ADWD 63: The Sacrifice", "score": "Score: 8.44"}
{"title": "A Dance with Dragons", "chapter": "ADWD 64: Victarion I", "score": "Score: 8.23"}
{"title": "A Dance with Dragons", "chapter": "ADWD 65: The Ugly Little Girl", "score": "Score: 8.56"}
{"title": "A Dance with Dragons", "chapter": "ADWD 66: Cersei II", "score": "Score: 8.64"}
{"title": "A Dance with Dragons", "chapter": "ADWD 67: Tyrion XII", "score": "Score: 7.80"}
{"title": "A Dance with Dragons", "chapter": "ADWD 68: The Kingbreaker", "score": "Score: 9.13"}
{"title": "A Dance with Dragons", "chapter": "ADWD 69: The Dragontamer", "score": "Score: 8.24"}
{"title": "A Dance with Dragons", "chapter": "ADWD 70: Jon XIII", "score": "Score: 7.68"}
{"title": "A Dance with Dragons", "chapter": "ADWD 71: The Queen's Hand", "score": "Score: 8.11"}
{"title": "A Dance with Dragons", "chapter": "ADWD 72: Daenerys X", "score": "Score: 7.57"}
{"title": "A Dance with Dragons", "chapter": "ADWD 73: Epilogue", "score": "Score: 9.23"}
{"title": "A Storm of Swords", "chapter": "ASOS 1: Prologue", "score": "Score: 8.02"}
{"title": "A Storm of Swords", "chapter": "ASOS 2: Jaime I", "score": "Score: 7.68"}
{"title": "A Storm of Swords", "chapter": "ASOS 3: Catelyn I", "score": "Score: 6.67"}
{"title": "A Storm of Swords", "chapter": "ASOS 4: Arya I", "score": "Score: 6.91"}
{"title": "A Storm of Swords", "chapter": "ASOS 5: Tyrion I", "score": "Score: 8.01"}
{"title": "A Storm of Swords", "chapter": "ASOS 6: Davos I", "score": "Score: 7.23"}
{"title": "A Storm of Swords", "chapter": "ASOS 7: Sansa I", "score": "Score: 7.76"}
{"title": "A Storm of Swords", "chapter": "ASOS 8: Jon I", "score": "Score: 7.99"}
{"title": "A Storm of Swords", "chapter": "ASOS 9: Daenerys I", "score": "Score: 7.85"}
{"title": "A Storm of Swords", "chapter": "ASOS 10: Bran I", "score": "Score: 7.23"}
{"title": "A Storm of Swords", "chapter": "ASOS 11: Davos II", "score": "Score: 7.80"}
{"title": "A Storm of Swords", "chapter": "ASOS 12: Jaime II", "score": "Score: 7.68"}
{"title": "A Storm of Swords", "chapter": "ASOS 13: Tyrion II", "score": "Score: 6.33"}
{"title": "A Storm of Swords", "chapter": "ASOS 14: Arya II", "score": "Score: 7.73"}
{"title": "A Storm of Swords", "chapter": "ASOS 15: Catelyn II", "score": "Score: 7.30"}
{"title": "A Storm of Swords", "chapter": "ASOS 16: Jon II", "score": "Score: 7.54"}
{"title": "A Storm of Swords", "chapter": "ASOS 17: Sansa II", "score": "Score: 6.78"}
{"title": "A Storm of Swords", "chapter": "ASOS 18: Arya III", "score": "Score: 6.93"}
{"title": "A Storm of Swords", "chapter": "ASOS 19: Samwell I", "score": "Score: 8.63"}
{"title": "A Storm of Swords", "chapter": "ASOS 20: Tyrion III", "score": "Score: 8.31"}
{"title": "A Storm of Swords", "chapter": "ASOS 21: Catelyn III", "score": "Score: 8.11"}
{"title": "A Storm of Swords", "chapter": "ASOS 22: Jaime III", "score": "Score: 8.65"}
{"title": "A Storm of Swords", "chapter": "ASOS 23: Arya IV", "score": "Score: 7.33"}
{"title": "A Storm of Swords", "chapter": "ASOS 24: Daenerys II", "score": "Score: 7.84"}
{"title": "A Storm of Swords", "chapter": "ASOS 25: Bran II", "score": "Score: 8.87"}
{"title": "A Storm of Swords", "chapter": "ASOS 26: Davos III", "score": "Score: 7.85"}
{"title": "A Storm of Swords", "chapter": "ASOS 27: Jon III", "score": "Score: 7.80"}
{"title": "A Storm of Swords", "chapter": "ASOS 28: Daenerys III", "score": "Score: 9.20"}
{"title": "A Storm of Swords", "chapter": "ASOS 29: Sansa III", "score": "Score: 8.18"}
{"title": "A Storm of Swords", "chapter": "ASOS 30: Arya V", "score": "Score: 7.30"}
{"title": "A Storm of Swords", "chapter": "ASOS 31: Jon IV", "score": "Score: 7.29"}
{"title": "A Storm of Swords", "chapter": "ASOS 32: Jaime IV", "score": "Score: 7.90"}
{"title": "A Storm of Swords", "chapter": "ASOS 33: Tyrion IV", "score": "Score: 7.09"}
{"title": "A Storm of Swords", "chapter": "ASOS 34: Samwell II", "score": "Score: 8.53"}
{"title": "A Storm of Swords", "chapter": "ASOS 35: Arya VI", "score": "Score: 8.45"}
{"title": "A Storm of Swords", "chapter": "ASOS 36: Catelyn IV", "score": "Score: 7.02"}
{"title": "A Storm of Swords", "chapter": "ASOS 37: Davos IV", "score": "Score: 8.56"}
{"title": "A Storm of Swords", "chapter": "ASOS 38: Jaime V", "score": "Score: 8.92"}
{"title": "A Storm of Swords", "chapter": "ASOS 39: Tyrion V", "score": "Score: 8.39"}
{"title": "A Storm of Swords", "chapter": "ASOS 40: Arya VII", "score": "Score: 7.26"}
{"title": "A Storm of Swords", "chapter": "ASOS 41: Bran III", "score": "Score: 7.48"}
{"title": "A Storm of Swords", "chapter": "ASOS 42: Jon V", "score": "Score: 8.27"}
{"title": "A Storm of Swords", "chapter": "ASOS 43: Daenerys IV", "score": "Score: 8.37"}
{"title": "A Storm of Swords", "chapter": "ASOS 44: Arya VIII", "score": "Score: 7.47"}
{"title": "A Storm of Swords", "chapter": "ASOS 45: Jaime VI", "score": "Score: 8.21"}
{"title": "A Storm of Swords", "chapter": "ASOS 46: Catelyn V", "score": "Score: 7.41"}
{"title": "A Storm of Swords", "chapter": "ASOS 47: Samwell III", "score": "Score: 8.25"}
{"title": "A Storm of Swords", "chapter": "ASOS 48: Arya IX", "score": "Score: 7.51"}
{"title": "A Storm of Swords", "chapter": "ASOS 49: Jon VI", "score": "Score: 7.88"}
{"title": "A Storm of Swords", "chapter": "ASOS 50: Catelyn VI", "score": "Score: 7.96"}
{"title": "A Storm of Swords", "chapter": "ASOS 51: Arya X", "score": "Score: 7.42"}
{"title": "A Storm of Swords", "chapter": "ASOS 52: Catelyn VII", "score": "Score: 9.11"}
{"title": "A Storm of Swords", "chapter": "ASOS 53: Arya XI", "score": "Score: 8.26"}
{"title": "A Storm of Swords", "chapter": "ASOS 54: Tyrion VI", "score": "Score: 8.37"}
{"title": "A Storm of Swords", "chapter": "ASOS 55: Davos V", "score": "Score: 7.79"}
{"title": "A Storm of Swords", "chapter": "ASOS 56: Jon VII", "score": "Score: 8.48"}
{"title": "A Storm of Swords", "chapter": "ASOS 57: Bran IV", "score": "Score: 8.21"}
{"title": "A Storm of Swords", "chapter": "ASOS 58: Daenerys V", "score": "Score: 8.41"}
{"title": "A Storm of Swords", "chapter": "ASOS 59: Tyrion VII", "score": "Score: 7.51"}
{"title": "A Storm of Swords", "chapter": "ASOS 60: Sansa IV", "score": "Score: 7.97"}
{"title": "A Storm of Swords", "chapter": "ASOS 61: Tyrion VIII", "score": "Score: 9.20"}
{"title": "A Storm of Swords", "chapter": "ASOS 62: Sansa V", "score": "Score: 8.22"}
{"title": "A Storm of Swords", "chapter": "ASOS 63: Jaime VII", "score": "Score: 7.86"}
{"title": "A Storm of Swords", "chapter": "ASOS 64: Davos VI", "score": "Score: 8.13"}
{"title": "A Storm of Swords", "chapter": "ASOS 65: Jon VIII", "score": "Score: 8.26"}
{"title": "A Storm of Swords", "chapter": "ASOS 66: Arya XII", "score": "Score: 7.51"}
{"title": "A Storm of Swords", "chapter": "ASOS 67: Tyrion IX", "score": "Score: 8.20"}
{"title": "A Storm of Swords", "chapter": "ASOS 68: Jaime VIII", "score": "Score: 7.62"}
{"title": "A Storm of Swords", "chapter": "ASOS 69: Sansa VI", "score": "Score: 7.69"}
{"title": "A Storm of Swords", "chapter": "ASOS 70: Jon IX", "score": "Score: 8.10"}
{"title": "A Storm of Swords", "chapter": "ASOS 71: Tyrion X", "score": "Score: 9.29"}
{"title": "A Storm of Swords", "chapter": "ASOS 72: Daenerys VI", "score": "Score: 8.22"}
{"title": "A Storm of Swords", "chapter": "ASOS 73: Jaime IX", "score": "Score: 8.32"}
{"title": "A Storm of Swords", "chapter": "ASOS 74: Jon X", "score": "Score: 8.84"}
{"title": "A Storm of Swords", "chapter": "ASOS 75: Arya XIII", "score": "Score: 8.64"}
{"title": "A Storm of Swords", "chapter": "ASOS 76: Samwell IV", "score": "Score: 7.89"}
{"title": "A Storm of Swords", "chapter": "ASOS 77: Jon XI", "score": "Score: 8.26"}
{"title": "A Storm of Swords", "chapter": "ASOS 78: Tyrion XI", "score": "Score: 9.16"}
{"title": "A Storm of Swords", "chapter": "ASOS 79: Samwell V", "score": "Score: 8.15"}
{"title": "A Storm of Swords", "chapter": "ASOS 80: Jon XII", "score": "Score: 8.64"}
{"title": "A Storm of Swords", "chapter": "ASOS 81: Sansa VII", "score": "Score: 9.16"}
{"title": "A Storm of Swords", "chapter": "ASOS 82: Epilogue", "score": "Score: 8.95"}
{"title": "A Feast for Crows", "chapter": "AFFC 1: Prologue", "score": "Score: 8.00"}
{"title": "A Feast for Crows", "chapter": "AFFC 2: The Prophet", "score": "Score: 7.01"}
{"title": "A Feast for Crows", "chapter": "AFFC 3: The Captain Of Guards", "score": "Score: 7.60"}
{"title": "A Feast for Crows", "chapter": "AFFC 4: Cersei I", "score": "Score: 7.64"}
{"title": "A Feast for Crows", "chapter": "AFFC 5: Brienne I", "score": "Score: 6.62"}
{"title": "A Feast for Crows", "chapter": "AFFC 6: Samwell I", "score": "Score: 7.66"}
{"title": "A Feast for Crows", "chapter": "AFFC 7: Arya I", "score": "Score: 7.50"}
{"title": "A Feast for Crows", "chapter": "AFFC 8: Cersei II", "score": "Score: 7.84"}
{"title": "A Feast for Crows", "chapter": "AFFC 9: Jaime I", "score": "Score: 7.53"}
{"title": "A Feast for Crows", "chapter": "AFFC 10: Brienne II", "score": "Score: 6.65"}
{"title": "A Feast for Crows", "chapter": "AFFC 11: Sansa I", "score": "Score: 7.33"}
{"title": "A Feast for Crows", "chapter": "AFFC 12: The Kraken's Daughter", "score": "Score: 6.86"}
{"title": "A Feast for Crows", "chapter": "AFFC 13: Cersei III", "score": "Score: 7.31"}
{"title": "A Feast for Crows", "chapter": "AFFC 14: The Soiled Knight", "score": "Score: 6.80"}
{"title": "A Feast for Crows", "chapter": "AFFC 15: Brienne III", "score": "Score: 6.74"}
{"title": "A Feast for Crows", "chapter": "AFFC 16: Samwell II", "score": "Score: 6.58"}
{"title": "A Feast for Crows", "chapter": "AFFC 17: Jaime II", "score": "Score: 7.00"}
{"title": "A Feast for Crows", "chapter": "AFFC 18: Cersei IV", "score": "Score: 7.25"}
{"title": "A Feast for Crows", "chapter": "AFFC 19: The Iron Captain", "score": "Score: 7.06"}
{"title": "A Feast for Crows", "chapter": "AFFC 20: The Drowned Man", "score": "Score: 7.25"}
{"title": "A Feast for Crows", "chapter": "AFFC 21: Brienne IV", "score": "Score: 7.67"}
{"title": "A Feast for Crows", "chapter": "AFFC 22: The Queenmaker", "score": "Score: 7.44"}
{"title": "A Feast for Crows", "chapter": "AFFC 23: Arya II", "score": "Score: 7.59"}
{"title": "A Feast for Crows", "chapter": "AFFC 24: Alayne I", "score": "Score: 7.52"}
{"title": "A Feast for Crows", "chapter": "AFFC 25: Cersei V", "score": "Score: 7.22"}
{"title": "A Feast for Crows", "chapter": "AFFC 26: Brienne V", "score": "Score: 7.26"}
{"title": "A Feast for Crows", "chapter": "AFFC 27: Samwell III", "score": "Score: 7.57"}
{"title": "A Feast for Crows", "chapter": "AFFC 28: Jaime III", "score": "Score: 7.84"}
{"title": "A Feast for Crows", "chapter": "AFFC 29: Cersei VI", "score": "Score: 7.13"}
{"title": "A Feast for Crows", "chapter": "AFFC 30: The Reaver", "score": "Score: 7.43"}
{"title": "A Feast for Crows", "chapter": "AFFC 31: Jaime IV", "score": "Score: 7.55"}
{"title": "A Feast for Crows", "chapter": "AFFC 32: Brienne VI", "score": "Score: 7.88"}
{"title": "A Feast for Crows", "chapter": "AFFC 33: Cersei VII", "score": "Score: 7.38"}
{"title": "A Feast for Crows", "chapter": "AFFC 34: Jaime V", "score": "Score: 7.50"}
{"title": "A Feast for Crows", "chapter": "AFFC 35: Cat Of The Canals", "score": "Score: 8.05"}
{"title": "A Feast for Crows", "chapter": "AFFC 36: Samwell IV", "score": "Score: 8.30"}
{"title": "A Feast for Crows", "chapter": "AFFC 37: Cersei VIII", "score": "Score: 7.60"}
{"title": "A Feast for Crows", "chapter": "AFFC 38: Brienne VII", "score": "Score: 8.27"}
{"title": "A Feast for Crows", "chapter": "AFFC 39: Jaime VI", "score": "Score: 8.34"}
{"title": "A Feast for Crows", "chapter": "AFFC 40: Cersei IX", "score": "Score: 7.47"}
{"title": "A Feast for Crows", "chapter": "AFFC 41: The Princess In The Tower", "score": "Score: 7.92"}
{"title": "A Feast for Crows", "chapter": "AFFC 42: Alayne II", "score": "Score: 8.20"}
{"title": "A Feast for Crows", "chapter": "AFFC 43: Brienne VIII", "score": "Score: 8.48"}
{"title": "A Feast for Crows", "chapter": "AFFC 44: Cersei X", "score": "Score: 8.83"}
{"title": "A Feast for Crows", "chapter": "AFFC 45: Jaime VII", "score": "Score: 8.27"}
{"title": "A Feast for Crows", "chapter": "AFFC 46: Samwell V", "score": "Score: 8.15"}
{"title": "A Clash of Kings", "chapter": "ACOK 1: Prologue", "score": "Score: 8.34"}
{"title": "A Clash of Kings", "chapter": "ACOK 2: Arya I", "score": "Score: 7.75"}
{"title": "A Clash of Kings", "chapter": "ACOK 3: Sansa I", "score": "Score: 7.83"}
{"title": "A Clash of Kings", "chapter": "ACOK 4: Tyrion I", "score": "Score: 8.69"}
{"title": "A Clash of Kings", "chapter": "ACOK 5: Bran I", "score": "Score: 7.07"}
{"title": "A Clash of Kings", "chapter": "ACOK 6: Arya II", "score": "Score: 8.05"}
{"title": "A Clash of Kings", "chapter": "ACOK 7: Jon I", "score": "Score: 7.80"}
{"title": "A Clash of Kings", "chapter": "ACOK 8: Catelyn I", "score": "Score: 7.51"}
{"title": "A Clash of Kings", "chapter": "ACOK 9: Tyrion II", "score": "Score: 8.74"}
{"title": "A Clash of Kings", "chapter": "ACOK 10: Arya III", "score": "Score: 7.70"}
{"title": "A Clash of Kings", "chapter": "ACOK 11: Davos I", "score": "Score: 8.72"}
{"title": "A Clash of Kings", "chapter": "ACOK 12: Theon I", "score": "Score: 8.28"}
{"title": "A Clash of Kings", "chapter": "ACOK 13: Daenerys I", "score": "Score: 7.40"}
{"title": "A Clash of Kings", "chapter": "ACOK 14: Jon II", "score": "Score: 6.49"}
{"title": "A Clash of Kings", "chapter": "ACOK 15: Arya IV", "score": "Score: 8.68"}
{"title": "A Clash of Kings", "chapter": "ACOK 16: Tyrion III", "score": "Score: 8.40"}
{"title": "A Clash of Kings", "chapter": "ACOK 17: Bran II", "score": "Score: 7.30"}
{"title": "A Clash of Kings", "chapter": "ACOK 18: Tyrion IV", "score": "Score: 8.79"}
{"title": "A Clash of Kings", "chapter": "ACOK 19: Sansa II", "score": "Score: 7.49"}
{"title": "A Clash of Kings", "chapter": "ACOK 20: Arya V", "score": "Score: 7.85"}
{"title": "A Clash of Kings", "chapter": "ACOK 21: Tyrion V", "score": "Score: 8.39"}
{"title": "A Clash of Kings", "chapter": "ACOK 22: Bran III", "score": "Score: 7.64"}
{"title": "A Clash of Kings", "chapter": "ACOK 23: Catelyn II", "score": "Score: 8.30"}
{"title": "A Clash of Kings", "chapter": "ACOK 24: Jon III", "score": "Score: 7.00"}
{"title": "A Clash of Kings", "chapter": "ACOK 25: Theon II", "score": "Score: 8.26"}
{"title": "A Clash of Kings", "chapter": "ACOK 26: Tyrion VI", "score": "Score: 8.70"}
{"title": "A Clash of Kings", "chapter": "ACOK 27: Arya VI", "score": "Score: 7.78"}
{"title": "A Clash of Kings", "chapter": "ACOK 28: Daenerys II", "score": "Score: 7.37"}
{"title": "A Clash of Kings", "chapter": "ACOK 29: Bran IV", "score": "Score: 7.57"}
{"title": "A Clash of Kings", "chapter": "ACOK 30: Tyrion VII", "score": "Score: 7.91"}
{"title": "A Clash of Kings", "chapter": "ACOK 31: Arya VII", "score": "Score: 8.05"}
{"title": "A Clash of Kings", "chapter": "ACOK 32: Catelyn III", "score": "Score: 8.21"}
{"title": "A Clash of Kings", "chapter": "ACOK 33: Sansa III", "score": "Score: 7.93"}
{"title": "A Clash of Kings", "chapter": "ACOK 34: Catelyn IV", "score": "Score: 8.61"}
{"title": "A Clash of Kings", "chapter": "ACOK 35: Jon IV", "score": "Score: 6.83"}
{"title": "A Clash of Kings", "chapter": "ACOK 36: Bran V", "score": "Score: 7.90"}
{"title": "A Clash of Kings", "chapter": "ACOK 37: Tyrion VIII", "score": "Score: 8.07"}
{"title": "A Clash of Kings", "chapter": "ACOK 38: Theon III", "score": "Score: 7.88"}
{"title": "A Clash of Kings", "chapter": "ACOK 39: Arya VIII", "score": "Score: 7.67"}
{"title": "A Clash of Kings", "chapter": "ACOK 40: Catelyn V", "score": "Score: 7.56"}
{"title": "A Clash of Kings", "chapter": "ACOK 41: Daenerys III", "score": "Score: 6.93"}
{"title": "A Clash of Kings", "chapter": "ACOK 42: Tyrion IX", "score": "Score: 8.25"}
{"title": "A Clash of Kings", "chapter": "ACOK 43: Davos II", "score": "Score: 9.00"}
{"title": "A Clash of Kings", "chapter": "ACOK 44: Jon V", "score": "Score: 7.17"}
{"title": "A Clash of Kings", "chapter": "ACOK 45: Tyrion X", "score": "Score: 7.73"}
{"title": "A Clash of Kings", "chapter": "ACOK 46: Catelyn VI", "score": "Score: 7.00"}
{"title": "A Clash of Kings", "chapter": "ACOK 47: Bran VI", "score": "Score: 8.07"}
{"title": "A Clash of Kings", "chapter": "ACOK 48: Arya IX", "score": "Score: 8.50"}
{"title": "A Clash of Kings", "chapter": "ACOK 49: Daenerys IV", "score": "Score: 9.24"}
{"title": "A Clash of Kings", "chapter": "ACOK 50: Tyrion XI", "score": "Score: 8.10"}
{"title": "A Clash of Kings", "chapter": "ACOK 51: Theon IV", "score": "Score: 6.93"}
{"title": "A Clash of Kings", "chapter": "ACOK 52: Jon VI", "score": "Score: 7.26"}
{"title": "A Clash of Kings", "chapter": "ACOK 53: Sansa IV", "score": "Score: 6.02"}
{"title": "A Clash of Kings", "chapter": "ACOK 54: Jon VII", "score": "Score: 7.35"}
{"title": "A Clash of Kings", "chapter": "ACOK 55: Tyrion XII", "score": "Score: 7.18"}
{"title": "A Clash of Kings", "chapter": "ACOK 56: Catelyn VII", "score": "Score: 7.53"}
{"title": "A Clash of Kings", "chapter": "ACOK 57: Theon V", "score": "Score: 6.60"}
{"title": "A Clash of Kings", "chapter": "ACOK 58: Sansa V", "score": "Score: 5.76"}
{"title": "A Clash of Kings", "chapter": "ACOK 59: Davos III", "score": "Score: 7.92"}
{"title": "A Clash of Kings", "chapter": "ACOK 60: Tyrion XIII", "score": "Score: 7.73"}
{"title": "A Clash of Kings", "chapter": "ACOK 61: Sansa VI", "score": "Score: 6.74"}
{"title": "A Clash of Kings", "chapter": "ACOK 62: Tyrion XIV", "score": "Score: 7.90"}
{"title": "A Clash of Kings", "chapter": "ACOK 63: Sansa VII", "score": "Score: 6.50"}
{"title": "A Clash of Kings", "chapter": "ACOK 64: Daenerys V", "score": "Score: 7.61"}
{"title": "A Clash of Kings", "chapter": "ACOK 65: Arya X", "score": "Score: 7.10"}
{"title": "A Clash of Kings", "chapter": "ACOK 66: Sansa VIII", "score": "Score: 7.39"}
{"title": "A Clash of Kings", "chapter": "ACOK 67: Theon VI", "score": "Score: 8.46"}
{"title": "A Clash of Kings", "chapter": "ACOK 68: Tyrion XV", "score": "Score: 7.33"}
{"title": "A Clash of Kings", "chapter": "ACOK 69: Jon VIII", "score": "Score: 8.61"}
{"title": "A Clash of Kings", "chapter": "ACOK 70: Bran VII", "score": "Score: 8.11"}
{"title": "A Game of Thrones", "chapter": "AGOT 1: Prologue", "score": "Score: 9.06"}
{"title": "A Game of Thrones", "chapter": "AGOT 2: Bran I", "score": "Score: 8.55"}
{"title": "A Game of Thrones", "chapter": "AGOT 3: Catelyn I", "score": "Score: 7.47"}
{"title": "A Game of Thrones", "chapter": "AGOT 4: Daenerys I", "score": "Score: 7.63"}
{"title": "A Game of Thrones", "chapter": "AGOT 5: Eddard I", "score": "Score: 8.43"}
{"title": "A Game of Thrones", "chapter": "AGOT 6: Jon I", "score": "Score: 8.43"}
{"title": "A Game of Thrones", "chapter": "AGOT 7: Catelyn II", "score": "Score: 7.52"}
{"title": "A Game of Thrones", "chapter": "AGOT 8: Arya I", "score": "Score: 8.22"}
{"title": "A Game of Thrones", "chapter": "AGOT 9: Bran II", "score": "Score: 8.95"}
{"title": "A Game of Thrones", "chapter": "AGOT 10: Tyrion I", "score": "Score: 8.65"}
{"title": "A Game of Thrones", "chapter": "AGOT 11: Jon II", "score": "Score: 8.34"}
{"title": "A Game of Thrones", "chapter": "AGOT 12: Daenerys II", "score": "Score: 7.97"}
{"title": "A Game of Thrones", "chapter": "AGOT 13: Eddard II", "score": "Score: 8.06"}
{"title": "A Game of Thrones", "chapter": "AGOT 14: Tyrion II", "score": "Score: 8.39"}
{"title": "A Game of Thrones", "chapter": "AGOT 15: Catelyn III", "score": "Score: 7.78"}
{"title": "A Game of Thrones", "chapter": "AGOT 16: Sansa I", "score": "Score: 7.68"}
{"title": "A Game of Thrones", "chapter": "AGOT 17: Eddard III", "score": "Score: 8.43"}
{"title": "A Game of Thrones", "chapter": "AGOT 18: Bran III", "score": "Score: 8.70"}
{"title": "A Game of Thrones", "chapter": "AGOT 19: Catelyn IV", "score": "Score: 7.54"}
{"title": "A Game of Thrones", "chapter": "AGOT 20: Jon III", "score": "Score: 8.46"}
{"title": "A Game of Thrones", "chapter": "AGOT 21: Eddard IV", "score": "Score: 8.31"}
{"title": "A Game of Thrones", "chapter": "AGOT 22: Tyrion III", "score": "Score: 8.45"}
{"title": "A Game of Thrones", "chapter": "AGOT 23: Arya II", "score": "Score: 8.32"}
{"title": "A Game of Thrones", "chapter": "AGOT 24: Daenerys III", "score": "Score: 8.07"}
{"title": "A Game of Thrones", "chapter": "AGOT 25: Bran IV", "score": "Score: 8.16"}
{"title": "A Game of Thrones", "chapter": "AGOT 26: Eddard V", "score": "Score: 8.44"}
{"title": "A Game of Thrones", "chapter": "AGOT 27: Jon IV", "score": "Score: 8.08"}
{"title": "A Game of Thrones", "chapter": "AGOT 28: Eddard VI", "score": "Score: 8.28"}
{"title": "A Game of Thrones", "chapter": "AGOT 29: Catelyn V", "score": "Score: 7.95"}
{"title": "A Game of Thrones", "chapter": "AGOT 30: Sansa II", "score": "Score: 7.47"}
{"title": "A Game of Thrones", "chapter": "AGOT 31: Eddard VII", "score": "Score: 8.87"}
{"title": "A Game of Thrones", "chapter": "AGOT 32: Tyrion IV", "score": "Score: 8.48"}
{"title": "A Game of Thrones", "chapter": "AGOT 33: Arya III", "score": "Score: 8.67"}
{"title": "A Game of Thrones", "chapter": "AGOT 34: Eddard VIII", "score": "Score: 8.49"}
{"title": "A Game of Thrones", "chapter": "AGOT 35: Catelyn VI", "score": "Score: 7.56"}
{"title": "A Game of Thrones", "chapter": "AGOT 36: Eddard IX", "score": "Score: 8.99"}
{"title": "A Game of Thrones", "chapter": "AGOT 37: Daenerys IV", "score": "Score: 7.71"}
{"title": "A Game of Thrones", "chapter": "AGOT 38: Bran V", "score": "Score: 7.36"}
{"title": "A Game of Thrones", "chapter": "AGOT 39: Tyrion V", "score": "Score: 8.49"}
{"title": "A Game of Thrones", "chapter": "AGOT 40: Eddard X", "score": "Score: 8.34"}
{"title": "A Game of Thrones", "chapter": "AGOT 41: Catelyn VII", "score": "Score: 8.60"}
{"title": "A Game of Thrones", "chapter": "AGOT 42: Jon V", "score": "Score: 7.36"}
{"title": "A Game of Thrones", "chapter": "AGOT 43: Tyrion VI", "score": "Score: 8.15"}
{"title": "A Game of Thrones", "chapter": "AGOT 44: Eddard XI", "score": "Score: 9.03"}
{"title": "A Game of Thrones", "chapter": "AGOT 45: Sansa III", "score": "Score: 6.66"}
{"title": "A Game of Thrones", "chapter": "AGOT 46: Eddard XII", "score": "Score: 9.10"}
{"title": "A Game of Thrones", "chapter": "AGOT 47: Daenerys V", "score": "Score: 8.90"}
{"title": "A Game of Thrones", "chapter": "AGOT 48: Eddard XIII", "score": "Score: 8.92"}
{"title": "A Game of Thrones", "chapter": "AGOT 49: Jon VI", "score": "Score: 7.62"}
{"title": "A Game of Thrones", "chapter": "AGOT 50: Eddard XIV", "score": "Score: 9.19"}
{"title": "A Game of Thrones", "chapter": "AGOT 51: Arya IV", "score": "Score: 8.92"}
{"title": "A Game of Thrones", "chapter": "AGOT 52: Sansa IV", "score": "Score: 7.23"}
{"title": "A Game of Thrones", "chapter": "AGOT 53: Jon VII", "score": "Score: 8.48"}
{"title": "A Game of Thrones", "chapter": "AGOT 54: Bran VI", "score": "Score: 7.89"}
{"title": "A Game of Thrones", "chapter": "AGOT 55: Daenerys VI", "score": "Score: 8.61"}
{"title": "A Game of Thrones", "chapter": "AGOT 56: Catelyn VIII", "score": "Score: 7.36"}
{"title": "A Game of Thrones", "chapter": "AGOT 57: Tyrion VII", "score": "Score: 8.13"}
{"title": "A Game of Thrones", "chapter": "AGOT 58: Sansa V", "score": "Score: 7.01"}
{"title": "A Game of Thrones", "chapter": "AGOT 59: Eddard XV", "score": "Score: 9.09"}
{"title": "A Game of Thrones", "chapter": "AGOT 60: Catelyn IX", "score": "Score: 8.20"}
{"title": "A Game of Thrones", "chapter": "AGOT 61: Jon VIII", "score": "Score: 8.41"}
{"title": "A Game of Thrones", "chapter": "AGOT 62: Daenerys VII", "score": "Score: 7.77"}
{"title": "A Game of Thrones", "chapter": "AGOT 63: Tyrion VIII", "score": "Score: 7.91"}
{"title": "A Game of Thrones", "chapter": "AGOT 64: Catelyn X", "score": "Score: 8.05"}
{"title": "A Game of Thrones", "chapter": "AGOT 65: Daenerys VIII", "score": "Score: 8.09"}
{"title": "A Game of Thrones", "chapter": "AGOT 66: Arya V", "score": "Score: 8.87"}
{"title": "A Game of Thrones", "chapter": "AGOT 67: Bran VII", "score": "Score: 7.74"}
{"title": "A Game of Thrones", "chapter": "AGOT 68: Sansa VI", "score": "Score: 7.49"}
{"title": "A Game of Thrones", "chapter": "AGOT 69: Daenerys IX", "score": "Score: 7.60"}
{"title": "A Game of Thrones", "chapter": "AGOT 70: Tyrion IX", "score": "Score: 8.42"}
{"title": "A Game of Thrones", "chapter": "AGOT 71: Jon IX", "score": "Score: 8.25"}
{"title": "A Game of Thrones", "chapter": "AGOT 72: Catelyn XI", "score": "Score: 8.63"}
{"title": "A Game of Thrones", "chapter": "AGOT 73: Daenerys X", "score": "Score: 9.09"}
